project_name: opinionated-server
env_files:
    github_token: ~/.github_token
before:
    hooks:
        - go test ./...
        - golangci-lint run
builds:
    - id: lib
      skip: true
snapshot:
    name_template: "{{ .Tag }}-next"
changelog:
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^test:"
release:
    github:
        owner: jrockway
        name: opinionated-server
    ids:
        - lib
    draft: true
    prerelease: auto
    name_template: "opinionated-server v{{.Version}}"
    disable: false
source:
    enabled: false
