apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: ekglue-reader
rules:
    - apiGroups: [""]
      resources: ["nodes", "services"]
      verbs: ["get", "watch", "list"]
    - apiGroups: ["discovery.k8s.io"]
      resources: ["endpointslices"]
      verbs: ["get", "watch", "list"]
